### ISSUE TITLE
Postgres user/url

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#1]
1) dedicated user for db (not postgres root)
2) put database url, user & pw in ENV somehow, amend code for this

**Comment by joharohl** [comment]
Did a quick hack where the database url is returned from a function in utils.py. Works fine on ubuntu, unsure about other systems.

**Comment by rasmuse** [comment]
1) Dedicated user added by @joharohl  in vagrant environment.
2) URL is now read from environment variable "DATABASE_URL". Thanks @joharohl.
