### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#10]
Obviously it's already a problem that we're all always working on the `master` branch and everybody (myself included) keep committing broken stuff. I suggest that we try to keep the `master` branch runnable and create a second permanent branch `develop` for all active development and that we try to locally always use separate branches for new features.

I have taken some inspiration from [this model](http://nvie.com/posts/a-successful-git-branching-model/). What are your thuoghts/comments/suggestions?

**Comment by joharohl** [comment]
Sounds good!

**Comment by jeinarsson** [comment]
Sure, I'll work on my branch discipline ;)

**Comment by joelgoop** [comment]
I have created a `develop` branch that you can merge more experimental features into. But I think it's good to keep separate feature branches for new stuff. Just remember to delete them after you merge (in the github repo as well: `git push origin --delete branch_name`).

I'm closing this issue for now, but we can re-open it if we want to discuss further!
