### ISSUE TITLE
Change deploy scheme to utilize more of docker hub and docker compose.

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#106]
Current setup uses custom scripts to do a lot of the deploy. This can be simplified a lot by using automated builds at docker hub and using docker-compose.

**Comment by rasmuse** [comment]
I don't fully understand the implications of this. But it sounds good, and I'll be happy if you explain the details when it's done :)

**Comment by joharohl** [comment]
More or less "fixed" by using travis. Travis tests the code, and if all is well builds a docker image that is pushed to dockerhub at `demokratikollen/web:<branch-name>`.

This will be used further down the pipeline for deploys, but can already be used to test out a certain version of demokratikollen locally.
