### ISSUE TITLE
numpy/matplotlib in python3

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#11]
I can't get pip to install this :(

**Comment by jeinarsson** [comment]
Sorry, I'm such a linux noob: apt-get is your friend.

**Comment by jeinarsson** [comment]
Well, I lied.
Seems simple enough: http://askubuntu.com/questions/509623/installation-procedure-for-numpy-and-other-python-3-4-packages-on-ubuntu-14-04

But, I do, and

```
(python3.4) vagrant@vagrant-ubuntu-trusty-32:~/app$ sudo apt-get install python
3-numpy
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-numpy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(python3.4) vagrant@vagrant-ubuntu-trusty-32:~/app$ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'numpy'
```

**Comment by joelgoop** [comment]
It's not a virtualenv thing? What if you run `deactivate` first?

**Comment by joharohl** [comment]
Yes. its virtual-env, it does not bring over the global packages. I have tried to compile it using pip too but failed. The work around is to deactivate and install `python3-sqlalchemy` and `python3-psycopg2` I'll have a look if it is possible to do it via pip but have not succeeded so far.

**Comment by joelgoop** [comment]
Another workaround would be to have Ansible run `apt-get install python3-numpy` first and then use the `--system-site-packages` option to `pyvenv` to include globally installed packages in the virtualenv. But it's not optimal since it would have some Python dependencies specified in requirements.txt and some not.

**Comment by joelgoop** [comment]
Ok, something is weird. `pip install numpy` works for me. I have also tried removing the `apt-get`s and just adding `numpy==1.9.0` to requirements.txt, and it also works with `vagrant destroy` => `vagrant up`. Importing `numpy` in the python 3 virtualenv is no problem. What errors is it that you get with `pip`?

**Comment by joharohl** [comment]
Trick was to not do `apt-get install ...` but `apt-get build-dep ...` to get it to install all dependencies for building matplotlib
