### ISSUE TITLE
Using Shelve for storing long database queries? 

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#12]
Creating networks and such seem to be quite time_consuming. How about using the build in shelve module? https://docs.python.org/3/library/shelve.html   

Should be relatively easy to migrate to a nosql database if the need should arise.

Alternatively go for mongodb straight away:
http://api.mongodb.org/python/current/
http://www.mongodb.org/

**Comment by jeinarsson** [comment]
At a glance, if anything then MongoDB.

But we could live with just having files on disks atm also, if it's a
hassle.

**Comment by joharohl** [comment]
I have started installing MongoDB. It is not working at the moment, I pushed a bit to early. So don't try to use it right now.

**Comment by joharohl** [comment]
And I am probably too tired. never pushed that part...but its coming soon.

**Comment by joharohl** [comment]
An implementation for a datastore is working in bdaa1817ef1a8c02a714f369acea2ab6ce899c73 now. Check out `create_covoting_matrix.py` and `utils.py` for a look at how it works. I changed a bit in the `utils.py` file as well so please have a look and see if you think its a good way to organise things.

**Comment by jeinarsson** [comment]
Great stuff! Merge to develop and close this issue?

**Comment by joharohl** [comment]
Merged and closed.
