### ISSUE TITLE
Coding style: Use spaces for indentation in Python code

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#13]
Python 3 disallows the mixture of tabs and spaces for indentation, so we have to agree on one style. I propose that we follow the convention (and PEP8 recommendation) of using four spaces. I have just changed this in the `develop` branch. See a3c61eb.

Sublime Text users, please check indentation settings here:
https://www.sublimetext.com/docs/3/indentation.html

**Comment by jeinarsson** [comment]
OK!
