### ISSUE TITLE
Populate ORM with "motioner"

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#24]
Assumes #16 is solved

**Comment by jeinarsson** [comment]
Note: Different types:

"följdmotion" av "kommite" eg http://www.riksdagen.se/sv/Dokument-Lagar/Forslag/Motioner/mot-20141538-med-anledning-a_H20238/

"fristående" av "enskild" eg http://www.riksdagen.se/sv/Dokument-Lagar/Forslag/Motioner/mot-20141543-Kontanter-pa-sk_H20243/

**Comment by joelgoop** [comment]
Another note on 'motioner':
- Some 'motioner' (and probably 'propositioner' as well) contain more than one proposal point ('förslagspunkt')
- These points may be treated in different 'betänkanden' (and even different committees).

Example: http://www.riksdagen.se/sv/Dokument-Lagar/Forslag/Motioner/Arbetsmarknadspolitik_GQ02A239/

Also relevant for #46.

**Comment by joelgoop** [comment]
Have added 'motioner' and 'propositioner' to the ORM structure as of 9832507e0d27a2780bbd778a4729a1369e92998f and tested the basic functionality of the  site with the new data. All appointments are now also in the ORM.
