### ISSUE TITLE
MongoDB store "Connection refused"

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#28]
The MongoDB store does not work for me.

I noticed it while trying to use the datastore in new branch fig-poll-freqs , but error is the same on create_covoting_matrix.py.

I'll try a complete vagrant destroy / up tonight, but the error right now is:
´´´
(python3.4) vagrant@vagrant-ubuntu-trusty-32:~/app$ python create_covoting_matr
ix.py
Traceback (most recent call last):
  File "/home/vagrant/.virtualenv/python3.4/lib/python3.4/site-packages/pymongo/
mongo_client.py", line 366, in **init**
    self._ensure_connected(True)
  File "/home/vagrant/.virtualenv/python3.4/lib/python3.4/site-packages/pymongo/
mongo_client.py", line 930, in _ensure_connected
    self.__ensure_member()
  File "/home/vagrant/.virtualenv/python3.4/lib/python3.4/site-packages/pymongo/
mongo_client.py", line 803, in __ensure_member
    member, nodes = self.__find_node()
  File "/home/vagrant/.virtualenv/python3.4/lib/python3.4/site-packages/pymongo/
mongo_client.py", line 894, in __find_node
    raise AutoReconnect(', '.join(errors))
pymongo.errors.AutoReconnect: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_covoting_matrix.py", line 94, in <module>
    datastore = MongoDBDatastore()
  File "/home/vagrant/app/utils.py", line 19, in **init**
    self.connection = MongoClient(self.dburl)
  File "/home/vagrant/.virtualenv/python3.4/lib/python3.4/site-packages/pymongo/
mongo_client.py", line 369, in **init**
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
(python3.4) vagrant@vagrant-ubuntu-trusty-32:~/app$
´´´

**Comment by joharohl** [comment]
I'll look into it. If  fig-poll-freqs is what I think it is we are doing the same thing. I'll remove my branch.

**Comment by joharohl** [comment]
It works for me. Might be a destroy/up that is needed. I updated the file as well. jsonify tries to sets and sends http headers as well so only works in the context of a flask app. json.dumps does the same thing but only returns a json string.

**Comment by jeinarsson** [comment]
destroy/up solved it, sorry.

I was confused abt dumps vs jsonify, thanks.

Another slightly unrelated intermittent problem: sometimes the DNS lookups from within the vb does not work (try python get_data.py or ping google.com), usually halt/up solves it.

**Comment by joharohl** [comment]
never happened for me but sounds like a glitch in virtualbox if halt/up solves it.
