### ISSUE TITLE
Refactor: rename /app to /demokratikollen and make python packages

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#29]
(here I mean by "/" the git root folder, not system root)

**_Symptom**_: I am making a complet mess out of /app/*.py . 

**_The problem**_ is that I cannot make a file in a subfolder, e g /app/jonas_crap/stuff.py, in which I import db_structure.py, because Python cannot import from ../ (unless I make per-file hacks).

**_I propose:**_

1) rename /app to /demokratikollen
2) create folders in /demokratikollen for different groups of functions, most importantly
3) make db_structure etc live in /demokratikollen/core
4) add / to pythons system package path in environment
5) put other stuff, like my horrible hacks for data mining in /demokratikollen/datamining and the likes

Then we should be able to have write for example

```
import demokratikollen.core.db_structure
from demokratikollen.utils import *
```

in our python files, whereever they live in relation to db_structure etc

**\* I fear **\* that renaming this folder will break stuff to hell, so therefore I assign @joharohl to perform the ceromony.

**Comment by joharohl** [comment]
sure.

**Comment by joharohl** [comment]
Done in branch packagize. Might be good if someone else have a try before merging with develop.

**Comment by joharohl** [comment]
Forgot some stuff in nginx.conf that is fixed now. An issue still exists that the static paths generated by Flask is not correct. Then nginx does not serve the files but unicorn which brakes (does not serve correct static files if they are updates) due to virtualbox bug.

**Comment by jeinarsson** [comment]
Tested and merged to develop and master.
