### ISSUE TITLE
Reorganize utils.py

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#31]
I think it would be better to make utils a package and turn the current static classes into modules, since modules are designed to perform the functions we want here. 

This means that instead of 

```
from demokratikollen.core.utils import PostgresUtils

PostgresUtils.whatever()
```

we can now use

```
import demokratikollen.core.utils as utils

utils.postgres.whatever()
```

I'll make an attempt at this, but since we have no standardized testing I would like you all to try some of the existing functionality and check if there are any problems, before we merge into `develop`.

**Comment by joelgoop** [comment]
Ok, unfortunately the example I wrote above is not correct Python code, so instead the usage will be something like

```
from demokratikollen.core.utils import postgres as pg_utils

pg_utils.whatever()
```

I have now pushed an attempt to a new branch. Please test it!

**Comment by joharohl** [comment]
Seems to work nicely in the webpart.

**Comment by rasmuse** [comment]
Yeah, I merged this into my `import_data` branch, and it works nicely there too. I merged this into develop now.
