### ISSUE TITLE
Cannot populate ORM (too much data?)

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#38]
`populate_orm.py` gets killed when I get to votes (prints `Killed` to the console and exits), with progress bar at 0. I guess this means that it cannot handle selecting all votes. We'll have to select them a few at a time if there is no way to tell Postgres to handle it automatically.

**Comment by joharohl** [comment]
It barely makes it with 1GB ram for the VM, but it takes forever. Would be nice with a way to comment out lines in url.txt that is not used.

**Comment by jeinarsson** [comment]
I made my own urls_dev.txt which has a fraction of the data. But anyway we
should think about
a) caching some of the downloads as to not be banned by data.riksdagen
b) incremental inserts of votes (see other issue abt initial deployment)
c) partitioning the inserting of votes using LIMIT and OFFSET in SQL (note:
current algorithm will fail if LIMIT breaks in middle of poll)

**Comment by jeinarsson** [comment]
Fixed by https://github.com/joelgoop/demokratikollen/commit/3005201598f8c6e24c772e40834cf01063ff1707
