### ISSUE TITLE
Git-fu

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#39]
Seems I make a mess of the commits sometimes.

Is there any way to clean up weird commits? If not, how should I solve this problem that happens every now and then:

I wanted to add the d7618a87a2900e53fc423ad1a45d7fd9512b8ecb commit to develop but @joelgoop managed to get ahead of me. So to be able to push I had to merge the remote to the local. Then I found I forgot to delete a debugging print that I then amended to the merge. That resulted in yet another request to merge with develop even though there was no difference.

**Comment by joelgoop** [comment]
[This flow chart](http://justinhileman.info/article/git-pretty/full/) says it all pretty well (credit to Jonas for finding it). 

There are lots of possibilities to go back and redo or change commits after the fact (see `git reset` and `rebase`), or undo changes by making new commits (`revert`). You can also just change the last commit (see `git commit --amend`). You can rewrite basically everything in the recorded history with `git`, but to quote [git documentation](http://git-scm.com/book/ch3-6.html), the basic rule is:

> Do not rebase commits that you have pushed to a public repository.

(also applies to `commit --amend`)

**Comment by joharohl** [comment]
Thanks! I guess the conclusion right now is to have it stay ugly and not repeat my mistake

**Comment by joelgoop** [comment]
Yes, I think it will drown in the rest of the ugliness in this project!

For easier `git`ing in the future, I found the following in [this presentation](https://presentate.com/bobthecow/talks/changing-history):

> I often end up with file changes which should ideally be split up into multiple commits, or even  committed into multiple branches. Partial-file commits are a lifesaver. Use them.
> Try the `-p` flag with `git add`, `git commit`, `git checkout`, `git reset`, and `git stash`.

Hadn't heard of this before, but it's something I've missed.

**Comment by rasmuse** [comment]
That flowchart is great. I am now using it as desktop background :)

**Comment by jeinarsson** [comment]
:D

![branch network win](https://cloud.githubusercontent.com/assets/610827/4740873/47fa54fe-5a11-11e4-9e2e-070b4e805155.png)

https://github.com/joelgoop/demokratikollen/network

I have lack of GitHub Markdown-fu though :/

**Comment by joharohl** [comment]
I win indeed.

**Comment by rasmuse** [comment]
Closing this issue for now. Please reopen the issue if you want to discuss git further.

**Comment by jeinarsson** [comment]
I just fucked my branch with git stash.

I had some uncommited stuff (not proud of) and wanted to merge in upstream develop. So I

```
git stash
git checkout develop
git pull
git checkout party-covoting
git merge develop
```

all fine, but then when I try 

```
git stash apply
```

I get some merge conflicts on urls.txt which I could resolve manually, add, and commit. All fine.
But then my stashed changes to party_covoting.py were not applied, so I try

```
git stash apply
```

again, whereupon history repeats itself: conflict on one file, I resolve merge conflicts, but then nothing more happens.

Now I dropped the stashed stuff and will rewrite the code instead. No biggie, but don't make my mistake, whatever it was. (I have not pushed any of this madness yet)

**Comment by joelgoop** [comment]
Yes, it's tricky to apply stashed changes if your branch has changed. So, you wanted to keep your changes uncommitted or why didn't you commit your stuff first and then merge? I'm not exactly sure where it went wrong, but generally it's hard to work with uncommitted code in git. Better to commit (you can always create a new branch) and work from there.
