### ISSUE TITLE
Use a single database server

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#4]
I think it would be easiest if we decide to either use MySQL or PostgreSQL. Is the SQL dump compatible with PostgreSQL? In that case we can use only PostgreSQL. Otherwise we either have to convert the data dump or switch SQLAlchemy over to MySQL.

**Comment by jeinarsson** [comment]
Sure, Postgres seems to be the OSS db of choice these days, so I vote that path.

The Riksdag has it's data in such disorder so it doesn't matter much. The SQL dump of course needs massage, I believe the easiest way is to re-import the .sql from data.riksdagen.se. Also let's keep an eye on http://utveckling.riksdagen.se/2011/samlade-synpunkter-och-kommentarer-fran-beta-riksdagen-se/

**Comment by joelgoop** [comment]
I guess we should try to write a script that imports the data without manual work. I have some time tonight, so I can take a look at it. 

Still no response on our questions. I guess they're busy `INSERT`ing all the new people into the database..

**Comment by joharohl** [comment]
I vote for postgres as well. Seems to be the most common so should give less problems down the road.

**Comment by jeinarsson** [comment]
I started a hack, see https://github.com/joelgoop/demokratikollen/commit/b772d25801bcf2cf13606fda798ae3eb0f986f79

**Comment by joelgoop** [comment]
Everything is now in PostgreSQL.
