### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#41]
When published we want analytics of the site, at minimum the simple stats:
IP addresses, geography if possible, platform/browser, referrer

I don't know what more exists "easily" and on the cheap, but individual page/figure popularities would be great.

**Comment by joharohl** [comment]
Would Google Analytics do? Or are big evil corporations out of the question?

**Comment by jeinarsson** [comment]
Will definitely do for now. At first I am mostly interested in simple
things: are parliament themselves visiting? major journalists? did they
google or did they get referred?

Let's do the whole track-every-move-analytics "later".

**Comment by joharohl** [comment]
GA seemed very easy to use and gives the basic stuff so is probably a good choice for 1.0

**Comment by joharohl** [comment]
We now have logging using newRelic which gives information on the performance of the app as well as traffic information. However, the data is only for 24h so will add google analytics as well soon.

**Comment by joharohl** [comment]
And google analytics...
