### ISSUE TITLE
Data: Missing 'dokutskottsforslag'

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#42]
I'm not sure if this is a problem at our side or in the original data, but I'll post it here anyway. When I import all polls from the last 'riksmöte' and all 'betänkanden' from 2010-13, a lot of the polls do not have a corresponding row in 'dokutskottsforslag'. 

It seems that either that data is simply missing in the original data or we somehow miss it when we download/insert. Is anything removed from the files during cleaning?

**Comment by joelgoop** [comment]
If I search with one of the missing 'votering_id' in the raw SQL file, it seems to be missing in the raw data. I will investigate some more when I have time and write to Riksdagen. I'll leave the issue here, since until this is fixed somehow, our possibilities to link decisions to documents are very limited.

**Comment by jeinarsson** [comment]
Does not

rm varchar(255),
beteckning varchar(255),
punkt integer,

also uniquely identify the poll "target"?

Eg
http://www.riksdagen.se/sv/Dokument-Lagar/Ovriga-dokument/Ovrigt-dokument/Votering-betankande-201314F_H119FiU20p1/

201314F_H119FiU20p1

http://data.riksdagen.se/voteringlista/?rm=2013%2F14&bet=FiU20&punkt=1&valkrets=&rost=&iid=&sz=500&utformat=xml&gruppering=

**Comment by jeinarsson** [comment]
Now I got confused: are you missing polls for documents, or documents for a
certain votering_id (poll), or both?

**Comment by joelgoop** [comment]
The problem is that the poll exists, but there is no corresponding 'dokutskottsforslag'. It's correct that rm/bet/punkt identifies a decision point. I haven't searched for that in the raw data, but it's not in the database. 

I don't know if there are other things than 'dokutskottsforslag' that can also be polled, but I can not find a 'votering_id' column anywhere else.

**Comment by joelgoop** [comment]
Ok, I can see that my previous comments are somewhat confusing. Maybe it's just too late to write anything sensible, but I checked some more and the fact is that the number of distinct 'votering_id' in the `votering` table with data from 2013/14 is much larger than the number of 'dokutskottsförslag' with `rm` 2013/14 that also contain a 'votering_id' (around 700 to a bit more than 100). 

Hope that makes sense.

**Comment by jeinarsson** [comment]
Right, so hypothesis: votering_id is something new and coming and is not yet implemented across the board.

Afaik, all polls correspond one-to-one with one 'punkt' in one 'betänkande', so that should not be the explanation.

Can you find examples where the data is missing the relation, but Riksdagen.se manages to show the poll? What does it say? Also, polls are available from data.riksdagen at http://data.riksdagen.se/votering/B0615B6C-6DDA-4508-B7BA-9068A6E0887E and so on.

Also, for some example, check out the corresponding data in http://data.riksdagen.se/dataset/votering/votering-201314.json.zip - is it just the same as the sql?

Finally, I think we have upcoming "competition" (although it's nothing to worry about): http://data.riksdagen.se/voteringlistagrupp/

**Comment by joelgoop** [comment]
No, sorry, my hypothesis is that some `dokutskottsforslag` (or 'punkt' in 'betänkande') are missing from the data. 

For example, 2013/14:MJU21:
https://www.riksdagen.se/sv/Dokument-Lagar/Utskottens-dokument/Betankanden/Arenden/201314/MJU21/

In our `riksdagen` db, in the `votering` table, there are four distinct `votering_id` corresponding to the four polls on riksdagen.se and all the votes from those polls. However, the table `dokutskottsforslag` contains nothing with `rm=2013/14` and `bet=MJU21`. So it's not only the `votering_id` that's missing, but the whole `dokutskottsforslag` row. Obviously, they have the data somewhere, since the connection is found on the linked page above, but as far as I can see it is not present in the data we have.

A quick `COUNT` shows that the number of `dokutskottsforslag` not decided by 'acklamation' (and actually all of them have a `votering_id`) are a lot fewer than the number of distinct `votering_id` in the `votering` table:

```
SELECT COUNT(*) FROM dokutskottsforslag WHERE beslutstyp!='acklamation' AND rm='2013/14'
68

SELECT COUNT(*) FROM dokutskottsforslag WHERE  votering_id!='' AND rm='2013/14'
68

SELECT COUNT(DISTINCT votering_id) FROM votering WHERE rm='2013/14'
713
```

I think it's time to write a blog post and e-mail Riksdagen.

**Comment by joelgoop** [comment]
Btw, the "HTML" output of the page you linked wasn't very useful, e.g.:
http://data.riksdagen.se/voteringlistagrupp/?rm=2013%2F14&bet=&punkt=&grupp1=C&grupp4=MP&utformat=HTML

The JSON looked a little bit nicer, but still.

**Comment by jeinarsson** [comment]
I noticed too. I agree with your diagnosis. Write them!

**Comment by joelgoop** [comment]
See http://demokratidata.blogspot.se/2014/10/utskottsforslag-saknas-i-riksdagens-sql.html. Feel free to edit if you have something to add or correct. Haven't had time to e-mail them yet, but I will!

**Comment by rasmuse** [comment]
http://data.riksdagen.se/voteringlista/ now seems to solve this issue.

See, e.g., http://data.riksdagen.se/voteringlista/?rm=2013%2F14&bet=MJU21&punkt=&valkrets=&rost=&iid=&sz=10000&utformat=json&gruppering=
