### ISSUE TITLE
Upgrade bootstrap?

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#43]
http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/

**Comment by joharohl** [comment]
Probably. We don't really use much of the features so the switch should be as easy as replacing the css and js files.

**Comment by joelgoop** [comment]
In the `bootstrap-template` branch we are already using the latest version. That is the version that will end up on the deployed site later, so I'll close this now.
