### ISSUE TITLE
Populate orm with 'propositioner'

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#46]
As of 52a599ffc6671cf6a0e337c3f7a628875bb0da7c, 'propositioner' docs are imported into `riksdagen` database, for example by running

```
python import_data.py data/urls.txt data/auto
```

It is my understanding that we need to put 'propositioner' docs into the ORM before launching 1.0. I'm guessing @joelgoop is best suited for this task. OK?

**Comment by joelgoop** [comment]
This is strongly related to #24, since 'propositioner' and 'motioner' are represented in the same way in the Riksdagen database.

**Comment by rasmuse** [comment]
OK. You are currently assigned to both issues. Is that OK? Do you need help?

**Comment by joelgoop** [comment]
No, I'm fine. They could actually be combined into one issue, but I'll just leave them as they are for now.

**Comment by rasmuse** [comment]
Don't combine them. You would have to do the same work but only get half as
much of the nice feeling of closing an issue.

**Comment by joelgoop** [comment]
Have added 'motioner' and 'propositioner' to the ORM structure as of 9832507e0d27a2780bbd778a4729a1369e92998f and tested the basic functionality of the  site with the new data. All appointments are now also in the ORM.
