### ISSUE TITLE
Improve search boxes

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#48]
My hallway usability testing (Esmeralda) shows that end users might find it inconvenient to remove the previous search text from the search box, for example on the Members page, when searching for members of parliament.

Possible solutions:
1) A little "x" symbol or something in the right hand part of the search field for removing all the text. See, e.g., the search field in Spotify.
2) The search field could automatically empty on click, or at least select all on click. Then you can just click once and start typing a new search.
3) After search, the search field could be select all:ed, for example like http://tyda.se/

(Other solutions also possible...)

**Comment by jeinarsson** [comment]
These pages were never meant as production, let's discuss what features should even be included first, make tests for them, and then create them. Feel free to make good examples if you feel like it in the meantime.
