### ISSUE TITLE
Clarify weekdays in figure 'voteringsfrekvens'

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#49]
My hallway usability testing (Esmeralda again) shows that the figure Voteringsfrekvens, binned on weekdays, is a little bit confusing: "What about Monday and Friday?"

At the moment, only Tuesday-Thursday are shown in the figure as they are the only days with recorded voting. The figure should probably include at least Monday and Friday, showing explicitly that they have zero count.

I'm adding milestone `1.0` to this issue. If we won't include that figure in 1.0, it can of course be removed from the milestone as well.

**Comment by jeinarsson** [comment]
These pages were never meant as production, let's discuss what features should even be included first, make tests for them, and then create them. Feel free to make good examples if you feel like it in the meantime.

**Comment by rasmuse** [comment]
OK, sounds fair. I guess my real problem is that I want somewhere to write
down ideas for new or enhanced features. Guess I will have to keep them in
a local document.

**Comment by jeinarsson** [comment]
Agreed, It's naive to think that we'll have final specs for any figures, so we definitely need a forum to discuss them as we go. Question: can we manage the whole spec for 1.0 as GH milestone issues? Or should we make some other (google?) document? Perhaps nice to keep it here?

For this particular case we also have #19 (closed), but let's at least wait with the milestone-stuff as to not fix things that won't be included. 

@joelgoop and I also discussed the search feature in the lines of a "spotify" like site-wide search (albums, tracks, ...) ~ (parties, groups, members,...), but let's hold that discussion until we clarified what will be on the site.

**Comment by rasmuse** [comment]
Yes, judging from your comment on site-wide search in this message, we
obviously need a place to discuss and note things down :)

Google docs is a simple and useful solution. Two other ideas come to mind:
1. We use the wiki feature on github. Pro: it's easy to keep things in one
place. Con: It's not really designed for discussion.
2. We use Trello. One list in the Demokratikollen board could be "UI
ideas", and a point on that list could be "Site-wide search". Each point on
a list gets a chronological "comments" list (not supporting nested
comments/trees). For each point on a list, you can write checklists, add
attachments, add labels, etc. The typical Trello use cases to some extent
overlap with the issues tracker on github, so we would have to decide on a
policy for what ends up where. Trello is fast and very responsive.
