### ISSUE TITLE
Path to 1.0

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#53]
Varning: Det här inlägget blev en jädra sörja av svenska och engelska. Ber om ursäkt på förhand.

As I have understood from discussions with pretty much all of you, perhaps not at the same time:
-  We want to put out a 1.0, preferably before christmas, and are willing to cut down the ideas to what's doable until then. 
-  We might want to do a 2.x, in which we probably must go to the xml-api instead of the not-so-frequently-updated datasets at data.riksdagen, but that's saved for a rainy winter.
- Depending on how that goes we may also continue the 1.x branch, say, by adding figures as we make them up. 1.0 could be pretty "skinny" content-wise, and 1.x adds meat to the bones, but perhaps no major data changes.
# Suggestion for 1.0 structure

In order to achieve a 1.0 we need to decide which "pages", or "views" the reader can see, and how the navigation works. While waiting for some numerics I jotted on paper, the following rough ideas:

The site has
1. A front page
2. "object pages", that is one per party, one per person, one per 'utskott' (perhaps)
3. "collection pages"
4. navigation, consisting of search and menus

The object pages are somewhat straight forward, and the front page I have no comments about yet. The collection pages and navigation are discussed in more detail below.
## Navigation

The navigation I see as a relatively normal head with logo (easiest: text in nice font, large period sign perhaps in color), and search:
![dsc_0081](https://cloud.githubusercontent.com/assets/610827/4904026/f5ebcc86-6444-11e4-88ad-b3be9052cb56.JPG)
Below the header there is one line of buttons leading to the "collection pages". I want to emphasize the search over "browsing" as the primary means of getting to members and parties. No drop downs.

The search is a spotify-like thing with "Top hit", parties, groups and members for rapid access to the objects.

If the head takes space, we can have it smaller when scrolling down. See eg http://www.kriesi.at/themes/enfold/
## Collection pages

Now, the "collection pages" I imagined are
- Partierna
- Förslagen
- Riksdagen

But this is also the level where I imagine putting "Budgeten" if that becomes a reality.
### Partierna

![dsc_0082](https://cloud.githubusercontent.com/assets/610827/4904195/53c64d30-6446-11e4-978b-c548fd83b983.JPG)
Could be the party bias figure and then just links to the party pages.
### Förslagen
- Sankey-figure motioner: parti, utskott, bifall/avslag
- Sankey propositioner: regeringen, departement, utskott, bifall/avslag
- Whatever more you can think of
  ![dsc_0083](https://cloud.githubusercontent.com/assets/610827/4904276/d904e0ec-6446-11e4-93c0-7afaf7ddfe7d.JPG)
### Riksdagen

Basically the overview of all members, main elements:
- Timeline with slider to choose an instant in history (default to today)
- Mandatfördelning över tiden
- The main graph area is populated by 349 party-colored circles, representing the members, then there is some kind of navigation (buttons, or something carousel-like) which puts the members as markers in different scatterplots.
- For example, they could initially be organised like Johans plot, ordered and by party. Then in the "next" plot in the navigation, the circles reorganise into gender, for example, and the "next" plot could be (ex 2) age on the x-axis and on the y-axis are the parties. One plot could be a map of Sweden with their origin, and so on. 
- If we have more detailed graphs of statistics they could appear below the timeline as one navigates through the carousel.
  ![dsc_0084](https://cloud.githubusercontent.com/assets/610827/4904473/f1aaaed2-6447-11e4-9235-6605728dcd7a.JPG)
  ![dsc_0086](https://cloud.githubusercontent.com/assets/610827/4904552/85868202-6448-11e4-8772-de0d2a283316.JPG)
## Parties and members

Simple pages with graphs, like
![dsc_0087](https://cloud.githubusercontent.com/assets/610827/4904558/8e92b104-6448-11e4-9889-4ee52e6e340a.JPG)
![dsc_0088](https://cloud.githubusercontent.com/assets/610827/4904560/8fd1e26a-6448-11e4-80d8-cf61310c0851.JPG)

**Comment by rasmuse** [comment]
First comment: Nice work! At a first glance I agree to this as a reasonable ambition for 1.0. It's important that 1.0 is interesting enough to make visitors want to come back, so I don't think we should have much less than this.

Will get back asap with comments, but I have to concentrate a little bit on work and packing for moving this week...

**Comment by jeinarsson** [comment]
Changes/mockups >> lists of comments!

**Comment by joelgoop** [comment]
Good stuff! I think this is a great starting point. Obviously, there will be a lot of details to work out along the way, but I think this is enough to get us going.

**Comment by jeinarsson** [comment]
Well, we'll see. I hope you will make it better ;)

But I and R meet tonight at least and can discuss it briefly. I believe
especially the "riksdagen" page needs thought, or splitting, as to not be
too complicated.

Regarding amount of content I think this is already quite ambitious if we
are serious about getting somewhere before christmas. To ship in ~6 weeks
of spare hours. we need to drop unneccessary stuff and Get Things Done(tm) (
http://www.joelonsoftware.com/articles/GuerrillaInterviewing3.html )

J

**Comment by joharohl** [comment]
Great stuff. I agree that the amount of content is probably more than we can handle before christmas. So the question is what to focus on. I am inclined to think that all component you have drawn up are needed, but we might want to prioritise what to show on each page. I have to think more on that.

That link mostly got me to feel useless, was it really necessary? :)

**Comment by jeinarsson** [comment]
If any comfort, I think that of all of us four, you are the one who Gets
Things Done(tm), while we tend to make
perfect-but-useless-whitepapers-on-subcomponents-no-one-cares-about-and-probably-will-be-discarded-for-2.0-anyway
(tm)... Carry on :)

Could Johan make an official "production-www" (name it something clever)
folder with some very simple behave tests? Perhaps inital tests just cover
navigation between the four main pages or so. Then I propose to be
disciplined and translate our decisions into behave tests before putting
_anything_ in that new shiny production-www.

Does anyone have the guts/knowledge to make a bootstrap template from my
sketches? No frills. Make the header black/white (rest of page is very
color intensive, and color carries political information, so let's keep
navigation/etc neutral in that sense). No animations or whatever. Just a
skeleton to work from, let's add rounded corners later if we want them.

I also realized that "Förslagen" page needs a timeline to select a time
span, like the one Joel usually looks at for the flight data analysis
(link?)

Got to go
J

**Comment by rasmuse** [comment]
@joelgoop and I have started working on the new bootstrap template.

Question for everyone: What about contact info? Most sites out on the interweb have an "About" link where you find meta-info such as contact details, and I think we should have something similar. 

My first idea is to create a small page footer present on each page, that either holds all that info, or with a link to http://demokratikollen.se/kontakt

Is that visible enough? We don't want to seem like we're trying to hide, but I'd rather keep focus on the site content than on us.

**Comment by jeinarsson** [comment]
I think demokratikollen.se/kontakt should exist, but let's make the link
minimal. Like a copyright notice in the footer or very weak in the header.

J

**Comment by joharohl** [comment]
Agreed.

**Comment by jeinarsson** [comment]
I'll close this now, let's open specific issues about the structure, if any, otherwise, keep hacking.
