### ISSUE TITLE
Testing of the webapp (and others?)

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#55]
I put up my old testing stuff in the setup-testing branch. It needs a little bit more work to be fully operational (e.g. a test database, perhaps some fixtures etc. ), but especially for the BDD part it is more than ready for tests to go in. The BDD tests needs to be put in .feature files in the `demokratikollen/www/features` folder. The nice thing with behave and BDD is that you can write the tests without actually thinking about any underlying logic.

Check out http://pythonhosted.org/behave/tutorial.html#feature-files for more info on how to write the feature files.

**Comment by jeinarsson** [comment]
I seem to screw this up all the time.

1) my pages work with gunicorn_debug, but not gunicorn_debug_nocache. The error seems to be that the ORM Database is different (and no tables exist) in the latter. Since the behave tests use _nocache, they fail. This seems to be the case also on Wercker. How did you do this when they did not fail? No db in tests? (see https://app.wercker.com/#buildstep/547260a6a60c33c27c24999b for log)

2) where (~ with which command) should I run the nosetests? At present HEAD in develop, in www I run "nosetests specs" and get errors involving files in "old_app". @joharohl said he fixed this, did I break it again when merging?

**Comment by joharohl** [comment]
It's not your fault really.
1. guincorn_debug_nocache was broken due to my poor programming. That alias ran the app in testing mode which then connects to the test database which is empty, giving you errors. I fixed the alias now in , do a `vagrant provision` and you should be good to go. I would advice to use werkzeug though, it gives more debug output in the browser if something brakes. 

Behave tests should use the testing version of gunicorn with an empty database. I just haven't thought about how to actually populate the database for the tests. A quick fix would be to run the production gunicorn instead but that would still fail on wercker which do not have a populated database. My idea was to dump the orm and db with minimal working data and import that when testing. The other option is to just insert enough data for each test case. I just needed to work with something a bit more fun. Anyway, I disabled behave tests on wercker for now to get passing builds. If you like to write behave tests now anyway, feel free to change which gunicorn runs in environment.py.
1. This is a bit weird. It is correct to run it the way you describe. Sounds like a typical `vagrant destroy/up` kind of fix, but I am not sure. They pass on wercker and on my machine so that's my guess anyhow.

PS. It is deploying right now. Should be up in 4 hours or so.

**Comment by joharohl** [comment]
Testing is kind of settled now from 248730f9a09cddda6fb10ed21628c1332b031660

Behave tests are kind of "easy" to implement.

Unittests on the other hand seem a bit more tricky, especially concerning calls to the db. 

For both models and routes it is relatively easy to mock away the db functionality and only test the logic of the code. Those types of tests are really good since they are simple and test only small portions of the code. Unfortunately, they assume that the database calls will generate the right kind of result and thus we still lack a good way to test that all the `db.session.query(...` calls are correct. 

I have not decided on a good way to test that aspect of the code (I have tried to look for some advice but haven't found any). I'm inclined to use the behave tests as a method for testing db calls, but I am not sure. It is possible to investigate the db beforehand and use that information to test that the db calls return what you expect but it feels like such tests would not be useful from a testing point of view. For example, to test the db call in data.gender_json, the test would need to do exactly the same call to the db and compare the results, thus no real information is gained (other than that you are running the same db calls). 

Any ideas on this matter? Or should we just accept that sqlalchemy gives you the data you expect? That coupled with normal "user" testing should get us pretty far.

**Comment by jeinarsson** [comment]
On Tue, Nov 25, 2014 at 8:48 PM, Johan Rohlén notifications@github.com
wrote:

> Any ideas on this matter? Or should we just accept that sqlalchemy gives
> you the data you expect? That coupled with normal "user" testing should get
> us pretty far.

I think that gets us far enough for now in this project, but it is an
interesting problem for upcoming projects. It seems like a fairly general
problem.

J

**Comment by rasmuse** [comment]
I agree with @jeinarsson. Closing this issue for now.
