### ISSUE TITLE
Caching web content is a hassle when developing

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#59]
@joelgoop and I have started working on #56 and were annoyed by the caching of output from the Flask webapp. Whenever we made a change and wanted to see the new content in the browser, we stopped the server, removed the `cache` folder and reran `werkzeug_debug`.

Are there any more convenient solutions? Maybe caching could just be disabled in debug mode? @joharohl?

**Comment by jeinarsson** [comment]
Hehe, I just commented the decorators...

**Comment by joharohl** [comment]
This is why we can't have nice things :)

get e246a9766290ad0924a265a7b3128c6bf99eb86e and do a `vagrant provision`. There are now two commands that uses the testing version of the app that has caching disabled: `werkzeug_debug_nocache` and `gunicorn_debug_nocache`
