### ISSUE TITLE
Forward port from PostgreSQL from vagrant to outside

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#6]

**Comment by joharohl** [comment]
This one should be fixed from a95cb5e6faf9795386168f04ac18edc221fdf86f. It works on my box but I know @jeinarsson had some issues. On the host, connecting to localhost:5433 with user=vagrant, password=demokratikollen should do it.

**Comment by joelgoop** [comment]
Now seems to be working both for me and @jeinarsson.
