### ISSUE TITLE
Ansible deployment

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#60]
Just FYI I am working on using Ansible to deploy the app instead of using the horrific bash script. It should be much more manageable, but the main feature is to rebuild the site in the background and do a quick switch once its done to keep downtime as low as possible. It will still work on a lot of convention over configuration so it would be good to get some things decided on before I get too carried away.

As far as I remember, these things can change during a deploy: 
1. The riksdagen database schema might change.  -> Rebuild Riksdagen -> Repopulate orm -> Redo calculations
2. The url.txt changed (or the files changed remotely) -> Rebuild/repopulate Riksdagen -> Repopulate orm -> Redo calculations
3. The db_struture.py might change -> Rebuild orm -> Redo calculations
4. The calculations might change -> Redo calculations

The first two can be taken care of by monitoring for changes in the `demokratikollen/data` dir. And any changes in the orm should be in the db_structure so that should be easy as well. The one that does not seem to have a clear structure at the moment are all the calculations. How about keeping all of those in the calculation dir. That way I can monitor that dir as well and even just scrape the dir and run all files.

**Comment by jeinarsson** [comment]
That is a good idea.

Joel has another use-case: he has a topoJSON-file which he wants dumped
into MongoDB. Can that also be classified as a "calculation".  If so he
simply checks in the json file in git, and makes a "calculation" which
imports the relevant parts into Mongo.

**Comment by joharohl** [comment]
Yes. Anything that needs to be done once and can be wrapped in a python script should work. I will most likely have to hand off the lengthier calculation to some sort of script due to the 25 min build limit on wercker but that shouldn't change the general idea.

**Comment by joharohl** [comment]
This is more or less done. The one thing that is missing is some way to monitor the deploy log. Right now, the only way is to log in to the vps and tail the log. I'll rather do something more interesting now though so if you feel the need to do some deploy debugging, send your public ssh key and i'll add you to the wercker account.

Deploys can be made manually in wercker. 

Closing the issue for now until a bug manifests :)
