### ISSUE TITLE
Real-time search box

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#62]
The requirements are
- [ ] Should be able to find
  - [x] Members
  - [x] Parties
  - [ ] Committees
  - [ ] Collection pages (?)
  - [ ] Connections between above, e.g., find members of V when typing 'vänster'
- [ ] Should group results in a sensible manner
- [x] Should generate a top hit

What do you think should happen when 'pressing enter' and how should longer lists of results be displayed?

**Comment by rasmuse** [comment]
I am rather fond of Spotify's search box behavior. The default behavior
when pressing return is very explicit: the top result is always "Show All
Results..." and leads to a search result page. This makes perfect sense in
Spotify, where there is typically a gazillion different matches for
whatever search phrase you come up with.

But in our application it could probably also be a decent default: If you
type "Jonas Sjöstedt" and hit return, you end up on a search results page,
with the top hit (the Members page for Sjöstedt, I guess) highlighted at
the top and some recent documents he has signed, etc. Let's say you are
really looking for the Member page, you start typing `jonas sjöst`, press
the "down" key once or twice down from "Show All Results..." and then you
press return and end up directly on the Member/Sjöstedt page.

**Comment by jeinarsson** [comment]
Our searches are a lot less content intensive compared to Spotify though. Can we live without a search results page? That will save us the pain of designing one.

**Comment by rasmuse** [comment]
Yes, at least for 1.0 IMHO.

**Comment by rasmuse** [comment]
(The comments are based on testing 2acd3dfc7963cd89ec05e998feb1c36a8327900e.)

@jeinarsson has made a promising first version of the search box backend. Pretty fast I must say!

However, there are sometimes confusing search results, e.g.:
- Search string `bil` (as in Bildt) gives top search result Ismail Kamil (FP).
- Search string `öra` (as in Göran) gives top result Alexandra Anstrell (M).

One possible lead: I think there is an error in the calculation of trigrams in `search.py`. The following line

```
[keyword["string"][k:] for k in range(3)]
```

will produce results like `'Gustav Fridolin' -> ['Gustav Fridolin', 'ustav Fridolin', 'stav Fridolin']`. Should it be something more like

```
>>> def get_ngrams(string, n):
...     return [string[k:k+n] for k in range(len(string)+1-n)]
... 
>>> print(get_ngrams('Gustav Fridolin', 3))
['Gus', 'ust', 'sta', 'tav', 'av ', 'v F', ' Fr', 'Fri', 'rid', 'ido', 'dol', 'oli', 'lin']
```

I just want to check this with @jeinarsson before changing anything, because I don't really understand all of the search code yet.

**Comment by jeinarsson** [comment]
The behaviour you describe is expected and correct from the algorithm. I can explain on the hangout, but right now I am making swiss cheese out of my apartment.

The fast fuzzy matching ranks all keywords. Then I have a very simple and arbitrary procedure to pick out the n best hits. One can easily make it "better" (whatever that means) by taking, say, the top 10% from the fuzzy ranking and applying some more expensive (Levenstein or so) measure to sort the results shown. But, main point of reply:

I think such minor improvements should wait until 1.1. It WORKS now. It does not give hilariously wrong results. Users don't generally search with 3 characters - you start typing, if your desired result is not shown yet you add a character.  When you type "bild" you get the bildts (only). When you type "öran" you get the Görans. By making it more complicated we risk spending days of work breaking stuff that already works. Let's leave it until the site is _publishable_.

As for search.py: The n-grams are actually generated client side now, I saved the server side version just in case it was too slow client side. Doing everything client side is easier if it works. (unicode stuff, same parser for query as keywords, etc).

**Comment by rasmuse** [comment]
That explains my confusion. I was bewildered that it would generally give such nice results with the n-gram generation looking like in search.py.

Anyway, I agree completely that the search behavior is good enough for 1.0. I was just browsing through the code out of curiosity and thought I had found a bug.

**Comment by rasmuse** [comment]
Closing this for now. Let's open a new search box issue when we want to add more functionality.
