### ISSUE TITLE
Gender-Plot-Json

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#66]
Create json generation for a gender plot as per 1.0

**Comment by joharohl** [comment]
If you want to have a look a the beta for gender figures. Have a look at 46f9b95c7552748fecfad0ec3286de7d4a20f50a

**Comment by rasmuse** [comment]
Nice figures, apart from the date bug that appeared on my system :)

A few quick comments:
- _Very_ nice that there is a date slider. That thing is useful for journalists and the likes. Definitely an added value compared to other sites.
- Chairs fig is great. I think we should have it in some form on the index page of "Riksdagen" in 1.0.
- Gender fig looks nice, but unfortunately not very useful. It's not easy to judge the gender distribution in the chamber, and ever harder to see the gender distribution in parties. I think some form of bar diagram would be better, and preferrably one where parties are stacked side by side.

**Comment by joharohl** [comment]
Silly you having the wrong system type :) Thanks for fixing the bug. The deploy is churning, but as long as riksdagen do not update the person.sql anytime soon it should be possible to do a small update.

I also felt that the gender fig maybe wasn't that useful. I think I tried to stay with the theme of having the circles represent each "ledamöt" which would move about depending on which "data" was selected. How about stacking them on top of each other, sort of like a bar chart?

**Comment by jeinarsson** [comment]
Great stuff! Love the slider, too! I agree the gender fig needs to be quantified in some way. It could be enough to just make a stacked bar between the symbols. (that is, two stacked bars, summing up to 100%) I think the grouping of the member markers is good eyecandy.

On my laptop the animations drag a little in firefox, but run smoothly in chrome.

**Comment by jeinarsson** [comment]
But I'd also say, feel free to add more figs before tweaking the existing ones. We might stumble on some common theme of how to do things if we throw them around a bit! They are all fair enough as-is (with some styling) for 1.0.

**Comment by joharohl** [comment]
How about something like this:
It would not be too hard to add actual number beneath for that extra qauntification, if needed.
![genderstacks](https://cloud.githubusercontent.com/assets/1255775/5163021/bfb118c4-73c6-11e4-9715-64496e64be8f.png)

**Comment by rasmuse** [comment]
Yeah, that's on the right track!

**Comment by joharohl** [comment]
On ice for now.
