### ISSUE TITLE
Appointments figure

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#71]
I started making a table of current and previous appointments for a member of parliament. (Mockup can be seen as of cc6ab27eabcfc2f64dd6ce02d8f6a8b0b327d283.) It's pretty hard to make it show all the relevant information while keeping it simple. @jeinarsson came up with the idea to make a timeline similar to a Gantt chart. I'll make one.

**Comment by jeinarsson** [comment]
Tummen upp!

**Comment by joelgoop** [comment]
While solving #24 and #46, I have now added all the appointments to the ORM and merged it into develop!

**Comment by joelgoop** [comment]
The figure looks awesome!!

I found the tooltip placement a bit strange (I don't know how if this is a bug or a chosen behavior), example below. Also, I have found it's a good idea to add `pointer-events: none` to the tooltip so it doesn't flicker when you touch it with the pointer (we should probably add this centrally somewhere in the sass files).

_Tooltip example:_ When I hover Stefan Attefall's chamber appointment between 2006 and 2010, the tooltip shows up to the left of the appointment line:
![attefall_cropped_1](https://cloud.githubusercontent.com/assets/1640080/5428726/150e1566-83cf-11e4-80bb-d53fa6f31a7f.png)

But when I move to left and hover the 2002 to 2006 appointment, the tooltip moves to the right (and is placed directly beneath the appointment line):
![attefall_cropped_2](https://cloud.githubusercontent.com/assets/1640080/5428727/15161c48-83cf-11e4-9187-541eab29b414.png)

**Comment by rasmuse** [comment]
Glad you like it :) I have a few improvements in the pipeline, but I agree it looks pretty slick already.

I know the tooltip placement is slightly awkward. What you are seeing is the intended behavior, but there is room for improvement as you have noticed. Problem is that, when you run it on a small screen (e.g. cell phone 320 pixels wide), the tooltip easily becomes too big and falls of the screen if you always place it directly below or above the line. So there is some logic in the chart saying "if you are on the left side of the chart, put the tooltip to the right", etc. And if you are in the middle of the figure, the tooltip is placed in the middle, too.

Suggestions are welcome, but to me priority one is to make the figure legible and useful on a mobile screen (and it really does work well down to 320 px wide at the moment!)

**Comment by rasmuse** [comment]
Oh, and I agree completely about the tooltip flickering. I am just now working on some general styling stuff like that.

**Comment by rasmuse** [comment]
I did some alpha testing with our friends P&S yesterday.

Basically very good feedback on the appointments timeline. It works on different devices. It is clearly legible. The testers understood immediately what the figure shows. They found it very nice and informative.

Needed improvements, also mentioned by @jeinarsson and @joelgoop:
- Some manual sorting of the rows is needed, most importantly to put "Riksdagsledamot" on the top line. Perhaps even mark it in a different color?
- Some more special cases needed to put dashed lines on "Suppleant" in some cases where there are currently solid lines. Perhaps also make "Ordförande" stick out somehow.
- Tooltip positioning is slightly awkward as mentioned in previous discussion.
