### ISSUE TITLE
Inform about cookies.

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#76]
The law requires a popup for first time visitors informing that cookies are used on the site. 

So before going 1.0. This needs to be implemented somehow.

**Comment by jeinarsson** [comment]
I love this law, because if you cannot place a cookie, you have to ask
every time they visit.

Or one can have three options: "We are using cookies, are you (a) OK (b)
Not OK (c) Not OK in general, but place one cookie to not ask me again."

Uh, btw, except analytics, are we using cookies?

**Comment by joharohl** [comment]
The funny thing is that you only have to inform that you use cookies, giving the user a choice is not part of the law.

Cookies are used for session data (or at least a session identifier). We probably don't need sessions but its there anyway, useful feature if the need arise. Cookies are also used for cross site forging detection when forms are used to make sure that form data is only coming from forms on our page and not from curls.

**Comment by jeinarsson** [comment]
Sounds good. It seems the interweb de facto standard is a colorful bar in
the top of the window.

There is a MIT Licensed jQuery-plugin here http://cookiesdirective.com/
Can we use it with our version of jQuery etc?

**Comment by rasmuse** [comment]
Thanks for fixing this one, @joharohl .

There is an issue though: The positioning of the cookie-info-bar is absolute and will therefore end up in the middle of the page when you start scrolling down. Anyone is free to fix it at their convenience, but if you don't I probably will do it pretty soon.

**Comment by joharohl** [comment]
Thanks. Only checked it on pages with too little content to scroll, dooh! Fixed in dd758a89ff907df7b560eba01067d3cc53eb4cd3. Should work in anything above IE7 which should be good enough for us.
