### ISSUE TITLE
Create a sitemap and register with Google (when the site is online)

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#77]
Google recommends building a sitemap and submitting it to them, especially if "Your site is new and has few external links to it." The standard format seems to be xml.

More info:
https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=6080646&rd=1

**Comment by joharohl** [comment]
Created sitemap generation for the site that should cover all pages available right now. Will register once with google once it is out.
