### ISSUE TITLE
VoteOption in the ORM

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#8]
On my box, the I get complaints that VoteOption does not exist. I see that there is an ENUM vote_option in the model for Vote and it works fine if I change code to use that instead of VoteOption.id.

Likewise with the new create_covoting_network.py in 098bedf79adaf4c63fd64b21aba7ef6014ac000b has this issue (using VoteOption.id)

Am I missing something? Are there ways to automagically generate that model from the Enum?

**Comment by joelgoop** [comment]
No, the VoteOption class has been removed and the options are now specified in an `ENUM`. The `app/populate_orm.py` script works as of 42c1136 if the `riksdagen` database is properly prepared. Instructions for doing that have been added to the `README.md`. `create_covoting_network.py` is not in working condition at the moment.

**Comment by joharohl** [comment]
Alright. As I though then. thanks.
