### ISSUE TITLE
Slow animations in Firefox.

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#93]
Animations of SVGs is super slow in Firefox to the point where at least the animations for the parilament figure is completely useless.

I have tried to look around for solutions and the only thing I have found so far is to:

a) detect Firefox and drop the animations.
b) try to measure the time it takes to animate.
c) Have the figure not animate.
d) Implement the figure with html elements.

a) is trivial but not very elegant. It also does not catch slow units such as a few year old phones. 

I tried b) but it turns out that this is not possible (at least in a simple way). The animations run ok in js, i.e. if an animation runs in 1000 ms, if you poll the attributes being animated they update in the time expected. The poor animation performance seems to be due to firefox and there is no feedback that can be used to detect the slow animation. Maybe if one hacks into the d3 code and try to intercept each animation call it could be done, but this approach might not be worth the effort. 

I am sort of leaning towards using c). Preferably, this could be detected for slow users as well by measuring the animation time since it then should be due to slow js execution, not poor animation performance? 

Any ideas, suggestions?

**Comment by jeinarsson** [comment]
How about (we talked abt this earlier)

e) make animations simpler, eg just fade in/out instead of long
translations. Even if they stutter it's not as bad.

**Comment by joharohl** [comment]
I tried that as well. Still really really bad performance, at least on my mac. The only thing that works is no animations.

**Comment by joharohl** [comment]
Ok. Demo live on the server. Untick the fancy animations checkbox to try with fading. It is a small mess to get proper cross-fade so only fade in on new elements at the moment, but it should give an indication of lag anyway. 

Please test in FF. Maybe its just FF + Mac that has these extreme issues. I basically get 2 frames (first and last of transition) with a 2-3 second delay between them.

**Comment by jeinarsson** [comment]
I couldn't see anything because I was busy playing with the new mouseovers
:)))

... , the fading animations are fine on my laptop with FF, it's a much much
better alternative than the translations and it serves the purpose of
showing the user who got exchanged.

But, there is a measurable delay (I "feel" it) between releasing the slider
and the animation starting. Perhaps that's the json request delay?

J

**Comment by jeinarsson** [comment]
In chrome it's really nice.

**Comment by joharohl** [comment]
OK. nice to hear. The initial delay is probably the AJAX, nothing to do about except putting a "fetching new data" somewhere. Lets see what the rest of the exhaustive  testing shows. If anyone can test on a Mac it would increase the dataset by 100%.

**Comment by rasmuse** [comment]
We have just tested both fancy and non-fancy animation on a MacBook Pro
(2010 model) in Firefox 34 and Safari 5.1.10, and in both cases the
animations run super smooth (among the smoothest performance I have seen
actually).

+1 for nice mouseovers, by the way.

**Comment by joharohl** [comment]
Very interesting. I also have a 2010 macbook pro and FF 35 and svg animations are unusable. I wonder what is causing this. I am gonna try to reinstall firefox and see what happens.

**Comment by joelgoop** [comment]
I have tested on another MacBook Pro (probably rather new, but not sure) and animations run smoothly. Didn't have time to check browser versions, unfortunately. However, the text animations only seemed to work in Safari. In FF the text just jumped into place.

**Comment by joharohl** [comment]
Solution for now is probably to go with  less "movy" animations and accept the somewhat poor performance for some units. Should still behave reasonably.
