### ISSUE TITLE
Invisible tooltip blocks slider on 'Riksdagen' figure

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#95]
When a tooltip is hidden it remains on the screen as an invisible clickable link. If it was displayed over another element of the page, e.g. the slider, it remains there even after it's hidden and can block the usage of that part and give confusing results, such as ending up on a member page when clicking on the slider. 

This is probably easily fixed by setting `display: none` when a tooltip is hidden.

**Comment by joharohl** [comment]
Nice catch! I'll fix.

**Comment by joharohl** [comment]
Fixed in 326f252d341e2db3494baf2f2b0e0827cf0288ce
