### ISSUE TITLE
Tweet button does different things for www.demokratikollen.se and demokratikollen.se

### ISSUE THREAD

**Issue by rasmuse** [demokratikollen/demokratikollen#99]
When I browse to http://www.demokratikollen.se/partierna I can see that somebody has tweeted the page. However, on http://demokratikollen.se/partierna (without www) there are no tweets reported. This might be the intended behavior of the Tweet button, but it was not the behavior I intended when I put it there... Ideally a tweet pointing to demokratikollen.se should do the exact same thing as a tweet pointing to www.demokratikollen.se.

**Comment by joharohl** [comment]
How about using a redirect in Flask so that requests to http://demokratikollen.se/x are redirected to http://www.demokratikollen.se/x

**Comment by joelgoop** [comment]
Maybe I should just redirect the domain so that demokratikollen.se is
always redirected to www?

**Comment by joelgoop** [comment]
I made an attempt, but I couldn't figure out the correct settings. I tried
a redirect, but it seems to always redirect to the starting page.

Is there a way to do it using Flask? I thought Flask was only aware of
routing within the app and not on a domain level?

**Comment by joharohl** [comment]
It gets domain info (accessible from the ´request´ object). I added a redirect, working from 2ddf70f2885f319020dbfe59c6d0e60f394c0125. If this is enough to fix the twitter issue we can close it.

**Comment by rasmuse** [comment]
Well done! :)
